name: CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Node ${{ matrix.node-version }} Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (ci or install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build TypeScript
        run: npm run build

      - name: Verify Plugin Metadata
        run: |
          node -e "
          const pkg = require('./package.json');
          if (!pkg.keywords.includes('homebridge-plugin')) {
            throw new Error('❌ Missing homebridge-plugin keyword');
          }
          console.log('✅ Plugin metadata check passed');"
